### ISSUE TITLE
Clean up Docs callout code

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/tanstack.com#1]
In my `main` branch right now, I have it set up for these changes:
- On all docs pages
  - on small screens you get the fixed, dismissible callout
  - on medium+ screens you get a persistent callout in a right sidebar
- On Query docs pages, you get the query.gg callout
- On all other docs pages (not Query), you get the Bytes callout

In order to do that, I moved the callout content into components and have the callouts duplicated:
- [Lines 292-298 of components/Docs.tsx](https://github.com/lynnandtonic/tanstack.com/blob/main/app/components/Docs.tsx#L291-L298) have the sidebar callout which is hidden by default and `block` for medium+
- [Lines 299-339](https://github.com/lynnandtonic/tanstack.com/blob/main/app/components/Docs.tsx#L299-L339) have the dismissible callout which is fixed by default and `hidden` for medium+

TODO:
- Is there a better way of setting this up so the callouts aren’t being duplicated?

**Comment by benadam11** [comment]
The code honestly looks fine ... a little duplication for stuff like this is usually the best way to do it.

**Comment by lynnandtonic** [comment]
@benadam11 Ah ok cool! Thanks for looking 🤗
